name: Build and Publish Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'
        
    # Download dependencies
    - run: go mod tidy
    
    # Build for Windows
    - name: Build Windows Binary
      run: |
        mkdir -p builds
        GOOS=windows GOARCH=amd64 go build -o builds/server.exe

    # Build for Default Architecture
    - name: Build Default Binary
      run: |
        mkdir -p builds
        go build -o builds/server

    # Create a Release and Upload Artifacts
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: builds/*
      env:
        GITHUB_TOKEN: ${{ secrets.MACHINE_TOKEN }}
