name: Go Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'
  
    #Download dependencies
    - run : go mod tidy

    # Build for Windows
    - name: Build Windows Binary
      run: |
        mkdir -p bin
        GOOS=windows GOARCH=amd64 go build -o bin/server.exe

    # Build for Default Architecture
    - name: Build Default Binary
      run: |
        mkdir -p bin
        go build -o bin/server

    # Upload binaries as artifacts
    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: go-binaries
        path: bin/