name: Build and Publish Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
 
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go Environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Download dependencies & make parent directory for builds
      run: |
          go mod tidy
          mkdir -p builds
    
    - name: Build Windows & Linux
      run: |
        GOOS=windows GOARCH=amd64 go build -o builds/server.exe
        go build -o builds/server
    
    - name: Configure Git
      run: |
        git config --global user.name "${{ secrets.MACHINE_USER_NAME }}"
        git config --global user.email  "${{ secrets.MACHINE_USER_EMAIL }}"

    - name: Create and Push Tag
      run: |
        tag_name="v$(date +'%Y%m%d%H%M%S')"
        echo "tag=$tag_name" >> $GITHUB_ENV
        git tag -a $tag_name -m "Automated release $tag_name"
        git push origin $tag_name
      
    
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: builds/*
        tag_name: ${{ env.tag }}  # Use the created tag
      env:
        GITHUB_TOKEN: ${{ secrets.MACHINE_TOKEN }}
      
